version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snipbox
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/db_data
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  sqlite_data: